// AUTO-GENERATED by scripts/build-meme.js — DO NOT EDIT BY HAND.
// Source of truth lives in src/cli/meme.source.js.
//
// v0.7.0 Group K2: the textual easter-egg payload (lyrics, team
// handles, watermark) is XOR-encoded + base64 in BLOB below. The
// decoder is intentionally simple — the goal is to defeat grep-based
// plagiarism scraping, not to provide cryptographic protection.
// Determined reverse-engineering can recover the data; the watermark
// survives and identifies origin in any copies. Please leave it in.

import React from "react";
import { Box, Text, useInput } from "ink";

const h = React.createElement;

const _K = Buffer.from([
  0x4b, 0x43, 0x37, 0x31, 0x2a, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2a, 0x66, 0x61, 0x74,
]);
const _BLOB = "MGFbSFgBAgFMXyhRY0ENGGs0VlheSAAcCkUAHEUIQ1hpFFIWWA1BARoXEh1OAwVUJC0XRUINQRALBBAbCEpDPSVjWERYSAUACwQeUQZENhFrM1ZDXkgVHQFFABxFCENYaQFCRQoBD1IBEAFTRg8EB2lvFWVCDRMXSRZTEgoSEwE/KxdFRUgHGwABUV8IMgkRayZZVQoBElIAAARRBkQgVD8sWl5YGg4FThIWU0cTEgBrMVJQSQBBFAEXUV8IMg5UKSYXWU8JExZMOF9RXgMAGWl5bBNqWFA0BxYbUQZEITUmJltYS0pNUC4kHQBPCiobKCZZEwZKITMaFxYGWURNVgsAVkNFBAgcCyYhPwhKQzQPKkFYWQEOHCoMARZJEg4GEzYVHQgoJgAPBhY0XwlDWGkDcENPDQ89HAQdFE9ETVYLC1ZdTCVDXkwlGBpeBQkRJW5SX00BDxcLF0dBCEpDNAcqW0hiHQAcCUdfUWorAAY+KFgTBkohIwcEHR9DCghWZ2F3QkUGBh8PClFfCCYVHC4sWRMGSiEqBwIGEghKQzQTGseupvdDXkwlChtCC0NYaQNNXk8SDhdMSVEzUB8ZACMmQ0NFBA1QM0lRBEsSBAYmIkVaCFJDOS1FscQKNg4YMgVYQ0dILx0ABhweRwMTFyIiWxEbRlFcXkWxxAqkyFQGJlpYXwVBXU4OGgdJDgQaZiZZVkMGBBccUUFT6NFBHD83R0IQR04VBxEbBkhIAhsmbFxYXgsJFwBIFh1NDw8RLjEDAwUDAl8NCRpRVw==";

function _decode() {
  const buf = Buffer.from(_BLOB, "base64");
  const out = Buffer.alloc(buf.length);
  for (let i = 0; i < buf.length; i++) out[i] = buf[i] ^ _K[i % _K.length];
  return JSON.parse(out.toString("utf-8"));
}

const _payload = _decode();
const LYRICS = _payload.lyrics;
const TEAM = _payload.team;
const __KC_MEME_WATERMARK__ = _payload.watermark;

export function MemeOverlay({ onDismiss }) {
  useInput((input, key) => {
    if (key.escape || key.return) onDismiss();
  });

  return h(Box, { flexDirection: "column", borderStyle: "round", borderColor: "magenta", paddingLeft: 2, paddingRight: 2, paddingTop: 1, paddingBottom: 1, marginTop: 1, marginBottom: 1 },
    h(Box, { flexDirection: "column" },
      ...LYRICS.map((line, i) =>
        h(Text, { key: `l-${i}`, color: "cyan", italic: true }, line),
      ),
    ),
    h(Text, null, ""),
    h(Text, { dimColor: true }, "─".repeat(60)),
    h(Text, null, ""),
    h(Text, { color: "yellow", bold: true },
      "Here's to all the smart minds that are/were part of our team:"),
    h(Text, null, ""),
    h(Box, { flexWrap: "wrap" },
      ...TEAM.map((handle, i) =>
        h(Text, { key: `t-${i}`, color: "green" }, `${handle}${i < TEAM.length - 1 ? ",  " : ""}`),
      ),
    ),
    h(Text, null, ""),
    h(Text, { dimColor: true }, "Press ESC or Enter to dismiss."),
    h(Text, { dimColor: true }, __KC_MEME_WATERMARK__),
  );
}
