import fs from "node:fs";
import path from "node:path";

const SCHEDULES_REL = "schedules.json";
const WRAPPERS_DIR_REL = path.join("scripts", "ingest");
const INGEST_LOG_REL = path.join("logs", "ingest.log");
const VALID_ID = /^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/;

/**
 * Per-session schedule registry + wrapper-script generator.
 *
 * KC defines fetch jobs (each is a shell command). For each enabled job,
 * Scheduler renders a self-contained wrapper script under
 * `workspace/scripts/ingest/<id>.sh`. The user installs the wrapper into
 * their crontab via `crontab -e`. Cron invokes the script directly — no
 * kc-beta runtime dependency, works while kc-beta is closed.
 *
 * The wrapper:
 *   - exports WORKSPACE / INPUT_DIR / PROJECT_DIR env vars
 *   - snapshots input/ filenames before running
 *   - runs the user's command
 *   - prefixes any new files in input/ with `<job-id>_<YYYYMMDD-HHMMSS>_`
 *   - appends to logs/ingest.log
 */
export class Scheduler {
  /**
   * @param {import('./workspace.js').Workspace} workspace
   */
  constructor(workspace) {
    this._workspace = workspace;
  }

  // --- registry ---

  load() {
    const p = this._abs(SCHEDULES_REL);
    if (!fs.existsSync(p)) return { version: 1, jobs: [] };
    try {
      const data = JSON.parse(fs.readFileSync(p, "utf-8"));
      if (!data.jobs) return { version: 1, jobs: [] };
      return data;
    } catch {
      return { version: 1, jobs: [] };
    }
  }

  save(state) {
    const p = this._abs(SCHEDULES_REL);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, JSON.stringify(state, null, 2), "utf-8");
    this._workspace.autoCommit?.(SCHEDULES_REL, "schedules");
  }

  list() {
    return this.load().jobs;
  }

  /**
   * Add a job. Returns { ok: true, job } or { ok: false, reason }.
   * @param {{id:string, command:string, description?:string, cron_hint?:string, enabled?:boolean}} input
   */
  add(input) {
    const id = (input.id || "").trim();
    const command = (input.command || "").trim();
    if (!VALID_ID.test(id)) return { ok: false, reason: `id must match ${VALID_ID} (got '${id}')` };
    if (!command) return { ok: false, reason: "command is required" };

    const state = this.load();
    if (state.jobs.find((j) => j.id === id)) {
      return { ok: false, reason: `job '${id}' already exists; remove first or pick another id` };
    }

    const job = {
      id,
      type: "shell",
      command,
      description: input.description || "",
      cron_hint: input.cron_hint || "",
      enabled: input.enabled !== false,
      created_at: new Date().toISOString(),
    };
    state.jobs.push(job);
    this.save(state);
    if (job.enabled) this.renderWrapper(job);
    return { ok: true, job };
  }

  remove(id) {
    const state = this.load();
    const before = state.jobs.length;
    state.jobs = state.jobs.filter((j) => j.id !== id);
    if (state.jobs.length === before) return { ok: false, reason: `no job '${id}'` };
    this.save(state);
    this._removeWrapper(id);
    return { ok: true };
  }

  setEnabled(id, enabled) {
    const state = this.load();
    const job = state.jobs.find((j) => j.id === id);
    if (!job) return { ok: false, reason: `no job '${id}'` };
    job.enabled = !!enabled;
    this.save(state);
    if (job.enabled) this.renderWrapper(job);
    else this._removeWrapper(id);
    return { ok: true, job };
  }

  // --- wrapper script ---

  /**
   * Render the per-job wrapper script. Returns absolute path.
   * @param {object} job
   */
  renderWrapper(job) {
    const wrappersDirAbs = this._abs(WRAPPERS_DIR_REL);
    fs.mkdirSync(wrappersDirAbs, { recursive: true });
    const scriptRel = path.join(WRAPPERS_DIR_REL, `${job.id}.sh`);
    const scriptAbs = this._abs(scriptRel);

    const wsAbs = this._workspace.cwd;
    const projectAbs = this._workspace.projectDir || "";
    const ingestLogAbs = this._abs(INGEST_LOG_REL);
    const inputDirAbs = path.join(wsAbs, "input");

    // Uses `find -newer` against a sentinel file to detect new arrivals.
    // Portable across macOS BSD find and GNU find (no -printf, no comm/process-sub).
    const body = [
      "#!/bin/sh",
      "# KC Agent ingestion wrapper",
      `# Job: ${job.id}`,
      `# Description: ${(job.description || "").replace(/[\r\n]/g, " ")}`,
      `# Generated: ${new Date().toISOString()}`,
      "# Do not edit by hand — regenerated by `schedule_fetch`.",
      "",
      "set -u",
      `WORKSPACE=${shQuote(wsAbs)}`,
      `INPUT_DIR=${shQuote(inputDirAbs)}`,
      `PROJECT_DIR=${shQuote(projectAbs)}`,
      `LOG_FILE=${shQuote(ingestLogAbs)}`,
      `JOB_ID=${shQuote(job.id)}`,
      'export WORKSPACE INPUT_DIR PROJECT_DIR',
      "",
      'mkdir -p "$INPUT_DIR" "$(dirname "$LOG_FILE")"',
      'TS=$(date -u +%Y%m%d-%H%M%S)',
      "",
      '# Sentinel file for `find -newer` to detect arrivals',
      'SENTINEL=$(mktemp -t kc_ingest_sentinel.XXXXXX) || exit 1',
      'sleep 1  # ensure mtime granularity',
      "",
      `echo "[$TS] job=$JOB_ID start" >> "$LOG_FILE"`,
      `{ ${job.command}; } >> "$LOG_FILE" 2>&1`,
      'EXIT_CODE=$?',
      "",
      "# Rename any files newer than the sentinel: prepend job id + timestamp.",
      "# Skip files already prefixed with this job id (idempotent re-runs).",
      'find "$INPUT_DIR" -maxdepth 1 -type f -newer "$SENTINEL" 2>/dev/null | while IFS= read -r f; do',
      '  base=$(basename "$f")',
      '  case "$base" in',
      `    "$\{JOB_ID\}_"*) continue ;;`,
      '  esac',
      '  mv "$f" "$INPUT_DIR/${JOB_ID}_${TS}_${base}"',
      'done',
      "",
      'rm -f "$SENTINEL"',
      `echo "[$TS] job=$JOB_ID exit=$EXIT_CODE" >> "$LOG_FILE"`,
      'exit $EXIT_CODE',
      "",
    ].join("\n");

    fs.writeFileSync(scriptAbs, body, "utf-8");
    fs.chmodSync(scriptAbs, 0o755);
    this._workspace.autoCommit?.(scriptRel, "wrapper");
    return scriptAbs;
  }

  _removeWrapper(id) {
    const scriptRel = path.join(WRAPPERS_DIR_REL, `${id}.sh`);
    const scriptAbs = this._abs(scriptRel);
    if (fs.existsSync(scriptAbs)) {
      fs.unlinkSync(scriptAbs);
      this._workspace.autoCommit?.(scriptRel, "wrapper-remove");
    }
  }

  /**
   * Generate paste-ready crontab lines for all enabled jobs.
   * If a job lacks `cron_hint`, the line is commented out with a hint to fill it in.
   * @returns {string}
   */
  formatCrontab() {
    const jobs = this.list().filter((j) => j.enabled);
    if (jobs.length === 0) return "(no enabled jobs to install)";

    const lines = [
      "# KC Agent ingestion jobs — install with `crontab -e` then paste these lines.",
      `# Generated ${new Date().toISOString()}`,
      "",
    ];
    for (const j of jobs) {
      const scriptAbs = this._abs(path.join(WRAPPERS_DIR_REL, `${j.id}.sh`));
      if (j.cron_hint) {
        lines.push(`# ${j.description || j.id}`);
        lines.push(`${j.cron_hint} ${scriptAbs}`);
      } else {
        lines.push(`# ${j.description || j.id} — set the schedule yourself (5 cron fields)`);
        lines.push(`# <minute> <hour> <day-of-month> <month> <day-of-week>  ${scriptAbs}`);
      }
      lines.push("");
    }
    return lines.join("\n").trimEnd();
  }

  /**
   * Tail of logs/ingest.log (last N lines), or empty string if missing.
   */
  tailLog(lines = 20) {
    const p = this._abs(INGEST_LOG_REL);
    if (!fs.existsSync(p)) return "";
    const body = fs.readFileSync(p, "utf-8");
    return body.split("\n").filter(Boolean).slice(-lines).join("\n");
  }

  /**
   * Count of files directly under input/ (excluding subdirs like archived/).
   */
  pendingInputCount() {
    const dir = path.join(this._workspace.cwd, "input");
    if (!fs.existsSync(dir)) return 0;
    try {
      return fs.readdirSync(dir, { withFileTypes: true })
        .filter((e) => e.isFile())
        .length;
    } catch {
      return 0;
    }
  }

  /**
   * Regenerate wrapper scripts for all enabled jobs. Used by
   * `engine.renameSession()` (Bug 3) — wrappers bake in absolute paths to
   * the workspace, so a rename needs them re-rendered with the new paths.
   *
   * Returns `{ regenerated, disabled, failed }`:
   *  - `regenerated`: ids of jobs whose wrappers were successfully re-rendered
   *  - `disabled`: ids of jobs we skipped because they're disabled (no wrapper expected)
   *  - `failed`: list of `{id, error}` for jobs whose render call threw
   * Splitting "skipped" into disabled vs failed lets the CLI surface render
   * failures (e.g. disk full) instead of silently swallowing them.
   */
  regenerateAllWrappers() {
    const out = { regenerated: [], disabled: [], failed: [] };
    for (const job of this.list()) {
      if (!job.enabled) { out.disabled.push(job.id); continue; }
      try {
        this.renderWrapper(job);
        out.regenerated.push(job.id);
      } catch (e) {
        out.failed.push({ id: job.id, error: e?.message || String(e) });
      }
    }
    return out;
  }

  // --- helpers ---

  _abs(rel) {
    return path.join(this._workspace.cwd, rel);
  }
}

/** POSIX shell-quote a string. */
function shQuote(s) {
  if (s === "") return "''";
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}
