#!/usr/bin/env node
// v0.7.0 Group K2: defensive-obfuscation build for the /meme easter egg.
//
// Reads `src/cli/meme.source.js` (the canonical dev source — kept in
// repo for humans to edit) and produces `src/cli/meme.js` (the shipped
// form — also committed, so dev mode works without running this first).
// The shipped form replaces the LYRICS / TEAM / __KC_MEME_WATERMARK__
// data with a single base64-encoded XOR blob plus an inline decoder.
//
// Goal: defeat casual `grep` plagiarism. If someone tries to scrape the
// team handles or watermark out of the npm package, they hit binary
// noise instead of plaintext. A motivated reverse engineer can still
// recover the data — the XOR key ships with the code — but they have
// to mean it. The watermark survives in the decoded structure and
// identifies origin in copies.
//
// Why not bytenode: meme.js imports react + ink (ESM-only). bytenode
// targets CJS bytecode, and bridging ESM imports through V8 bytecode
// would require an esbuild bundle step. Encoded-source achieves the
// same defensive goal with no extra build deps and no Node-version
// brittleness.
//
// Run: `npm run build:meme` (or auto via prepublishOnly).

import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(repoRoot, "src", "cli", "meme.source.js");
const outputPath = path.join(repoRoot, "src", "cli", "meme.js");

if (!fs.existsSync(sourcePath)) {
  console.error(`[build-meme] source not found: ${sourcePath}`);
  process.exit(1);
}

const source = fs.readFileSync(sourcePath, "utf-8");

// Extract LYRICS array, TEAM array, and __KC_MEME_WATERMARK__ string
// via narrow regex on the canonical layout in meme.source.js.
const lyricsMatch = source.match(/const LYRICS = (\[[\s\S]*?\]);/);
const teamMatch = source.match(/const TEAM = (\[[\s\S]*?\]);/);
const watermarkMatch = source.match(/const __KC_MEME_WATERMARK__\s*=\s*([\s\S]*?);/);

if (!lyricsMatch || !teamMatch || !watermarkMatch) {
  console.error("[build-meme] failed to extract LYRICS / TEAM / __KC_MEME_WATERMARK__");
  console.error("[build-meme] check meme.source.js layout against the regex assumptions");
  process.exit(1);
}

// Evaluate the array literals via Function constructor. Safe because
// meme.source.js is ours and we control its content.
const lyrics = new Function(`return ${lyricsMatch[1]};`)();
const team = new Function(`return ${teamMatch[1]};`)();
// watermark is concatenated string segments — eval as expression
const watermark = new Function(`return ${watermarkMatch[1]};`)();

// Encode payload: JSON → XOR with fixed 16-byte key → base64.
const PAYLOAD_KEY = Buffer.from([
  0x4b, 0x43, 0x37, 0x31, 0x2a, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2a, 0x66, 0x61, 0x74,
]); // not secret; defeats grep

function xorEncode(plain, key) {
  const out = Buffer.alloc(plain.length);
  for (let i = 0; i < plain.length; i++) {
    out[i] = plain[i] ^ key[i % key.length];
  }
  return out;
}

const payload = JSON.stringify({ lyrics, team, watermark });
const encoded = xorEncode(Buffer.from(payload, "utf-8"), PAYLOAD_KEY).toString("base64");

const generated = `// AUTO-GENERATED by scripts/build-meme.js — DO NOT EDIT BY HAND.
// Source of truth lives in src/cli/meme.source.js.
//
// v0.7.0 Group K2: the textual easter-egg payload (lyrics, team
// handles, watermark) is XOR-encoded + base64 in BLOB below. The
// decoder is intentionally simple — the goal is to defeat grep-based
// plagiarism scraping, not to provide cryptographic protection.
// Determined reverse-engineering can recover the data; the watermark
// survives and identifies origin in any copies. Please leave it in.

import React from "react";
import { Box, Text, useInput } from "ink";

const h = React.createElement;

const _K = Buffer.from([
  0x4b, 0x43, 0x37, 0x31, 0x2a, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2a, 0x66, 0x61, 0x74,
]);
const _BLOB = ${JSON.stringify(encoded)};

function _decode() {
  const buf = Buffer.from(_BLOB, "base64");
  const out = Buffer.alloc(buf.length);
  for (let i = 0; i < buf.length; i++) out[i] = buf[i] ^ _K[i % _K.length];
  return JSON.parse(out.toString("utf-8"));
}

const _payload = _decode();
const LYRICS = _payload.lyrics;
const TEAM = _payload.team;
const __KC_MEME_WATERMARK__ = _payload.watermark;

export function MemeOverlay({ onDismiss }) {
  useInput((input, key) => {
    if (key.escape || key.return) onDismiss();
  });

  return h(Box, { flexDirection: "column", borderStyle: "round", borderColor: "magenta", paddingLeft: 2, paddingRight: 2, paddingTop: 1, paddingBottom: 1, marginTop: 1, marginBottom: 1 },
    h(Box, { flexDirection: "column" },
      ...LYRICS.map((line, i) =>
        h(Text, { key: \`l-\${i}\`, color: "cyan", italic: true }, line),
      ),
    ),
    h(Text, null, ""),
    h(Text, { dimColor: true }, "─".repeat(60)),
    h(Text, null, ""),
    h(Text, { color: "yellow", bold: true },
      "Here's to all the smart minds that are/were part of our team:"),
    h(Text, null, ""),
    h(Box, { flexWrap: "wrap" },
      ...TEAM.map((handle, i) =>
        h(Text, { key: \`t-\${i}\`, color: "green" }, \`\${handle}\${i < TEAM.length - 1 ? ",  " : ""}\`),
      ),
    ),
    h(Text, null, ""),
    h(Text, { dimColor: true }, "Press ESC or Enter to dismiss."),
    h(Text, { dimColor: true }, __KC_MEME_WATERMARK__),
  );
}
`;

fs.writeFileSync(outputPath, generated, "utf-8");

const sizeBytes = Buffer.byteLength(generated, "utf-8");
const blobBytes = encoded.length;
console.log(`[build-meme] wrote ${path.relative(repoRoot, outputPath)} (${sizeBytes} bytes total, ${blobBytes} bytes blob)`);
console.log(`[build-meme] payload: ${lyrics.length} lyric lines, ${team.length} team handles, ${watermark.length}-char watermark`);
